### ISSUE TITLE
Numeric value out of range

### ISSUE THREAD

**Issue by karpstrucking** [fordav3/seat-payout#16]
Vol stumbled on this by accident because the loot log included someone moving around a bunch of blueprints

> SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'isk' at row 1 (SQL: insert into `seat_payout_payouts` (`character_name`, `item`, `quantity`, `isk`, `updated_at`, `created_at`) values (Shantra Wulffe, Covetor Blueprint, 3, 5928016136.8425, 2019-04-20 13:07:25, 2019-04-20 13:07:25))

**Comment by karpstrucking** [comment]
@fordav3 this change fixes this issue by no longer calculating payout for items not selected in the filter, but I suspect the actual underlying issue is that the column in the db needs to be modified to accept larger values - might be worth addressing in case we're logging anything in the billions down the road.

**Comment by starluneaux** [comment]
Yeah, I could have sworn that I fixed that a while back

**Comment by starluneaux** [comment]
I'll have to make a migration or something and change the type
